### PR TITLE
rewrite import path to use multiformats org's code

### PR DESCRIPTION
**Pull request by keks**

### CODE REVIEW

**Comment by Kubuxu** [comment]
Are you still interested in working on it?
I can take it over.

**Comment by keks** [comment]
Sorry for not responding earlier, had a terribly busy week. I thought this was finished? What do you want changed?

**Comment by keks** [comment]
Looks like I didn't update properly. This should be correct.

**Comment by keks** [comment]
I see, gx version mixup. On it now.

**Comment by keks** [comment]
I see, gx version mixup. On it now.

**Comment by keks** [comment]
Done

**Comment by Kubuxu** [comment]
I can't seem to resolve QmfRa79rtATpaaTxYdCAZfxbYyU4G6dEQa9RwWoGEpiiMS, but I seem to remember that it included version of multiaddr other released.

**Comment by keks** [comment]
I'm not sure what you mean but it's on the gateways now. Feel free to take a look!

**Comment by Stebalien** [comment]
@keks I assume this is now defunct?

**Comment by keks** [comment]
yup, thanks for pinging me

**Pull request closed without merging**
